# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1edee42f5896290e8dba4520884f677d10fc61de20423964d8433e880e34b92e82dde8f2666119085744778997b7055637f96857bca4e116c3610acb944821d1

test:
  secret_key_base: ca0b1734bae2b32e2b35a107623eb80a1ec0be56c206bf1073634a5b8c47b0a3c6f245a41b7258621a14bd165fc6eec3023dec37d5adb8764c3a3ee31cb77c19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
